#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rainbow
Version  : 2.1.0
Release  : 5
URL      : https://rubygems.org/downloads/rainbow-2.1.0.gem
Source0  : https://rubygems.org/downloads/rainbow-2.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# Rainbow
[![Build Status](https://travis-ci.org/sickill/rainbow.png?branch=master)](https://travis-ci.org/sickill/rainbow)
[![Code Climate](https://codeclimate.com/github/sickill/rainbow.png)](https://codeclimate.com/github/sickill/rainbow)
[![Coverage Status](https://coveralls.io/repos/sickill/rainbow/badge.png)](https://coveralls.io/r/sickill/rainbow)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rainbow-2.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-rainbow.gemspec

%build
gem build rubygem-rainbow.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rainbow-2.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rainbow-2.1.0
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rainbow-2.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/color.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/ext/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/global.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/legacy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/null_presenter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/presenter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/string_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/lib/rainbow/x11_color_names.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/rainbow.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/integration/instance_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/integration/rainbow_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/integration/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/support/presenter_shared_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/color_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/namespace_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/null_presenter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/presenter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/string_utils_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rainbow-2.1.0/spec/unit/wrapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rainbow-2.1.0.gemspec
