#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rainbow
Version  : 2.0.0
Release  : 2
URL      : https://rubygems.org/downloads/rainbow-2.0.0.gem
Source0  : https://rubygems.org/downloads/rainbow-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# Rainbow
[![Build Status](https://travis-ci.org/sickill/rainbow.png?branch=master)](https://travis-ci.org/sickill/rainbow)
[![Code Climate](https://codeclimate.com/github/sickill/rainbow.png)](https://codeclimate.com/github/sickill/rainbow)
[![Coverage Status](https://coveralls.io/repos/sickill/rainbow/badge.png)](https://coveralls.io/r/sickill/rainbow)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rainbow-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-rainbow.gemspec

%build
gem build rubygem-rainbow.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rainbow-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rainbow-2.0.0
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rainbow-2.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Object/Rainbow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Indexed/cdesc-Indexed.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Indexed/codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Indexed/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Indexed/num-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Named/cdesc-Named.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Named/color_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/Named/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/cdesc-RGB.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/code_from_rgb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/codes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/g-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/r-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/RGB/to_ansi_domain-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/cdesc-Color.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/ground-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Color/parse_hex_color-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/blink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/bright-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/colour-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/foreground-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/hide-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/italic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/InstanceMethods/underline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Ext/cdesc-Ext.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/bg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/blink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/bright-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/cdesc-NullPresenter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/fg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/foreground-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/hide-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/italic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/underline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/NullPresenter/yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/bg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/black-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/blink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/bright-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/cdesc-Presenter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/cyan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/fg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/foreground-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/hide-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/italic-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/magenta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/underline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/white-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Presenter/yellow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/RbConfig/cdesc-RbConfig.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/StringUtils/cdesc-StringUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/StringUtils/wrap_with_sgr-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Wrapper/cdesc-Wrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Wrapper/enabled-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Wrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/Wrapper/wrap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/cdesc-Rainbow.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/enabled%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/enabled-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/global-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Rainbow/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Sickill/Rainbow/cdesc-Rainbow.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Sickill/Rainbow/enabled%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Sickill/Rainbow/enabled-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/Sickill/cdesc-Sickill.ri
/usr/lib64/ruby/gems/2.2.0/doc/rainbow-2.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/Changelog.md
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/color.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/ext/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/global.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/legacy.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/null_presenter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/presenter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/string_utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/lib/rainbow/wrapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/rainbow.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/integration/instance_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/integration/rainbow_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/integration/string_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/support/presenter_shared_examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/color_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/namespace_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/null_presenter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/presenter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/string_utils_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rainbow-2.0.0/spec/unit/wrapper_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rainbow-2.0.0.gemspec
